### ISSUE TITLE
Commit in apps.json (yunohost app list) is 1 year old ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/cheky_ynh#20]
c.f. https://github.com/YunoHost/apps/blob/master/apps.json#L213

stills points to f93653c45dec675dca6f67cb0ffa1783c3ed8415 from May 2018 ... Consider to change it to 'HEAD' so that the last version is automatically used. From the README : 

>You can now put HEAD as revision. This way, you won't have to come and update this file each time you change things in your app. But this also means that any change to your master branch will be made available to everybody. Hence, when developing things which are not production-ready, if you use HEAD we strongly recommend that you develop in a testing branch (for instance) until you consider things stable enough to be merged in master.

**Comment by Gofannon** [comment]
Thanks. I will do the change once the **testing** version will be pushed to **master**

**Comment by Gofannon** [comment]
Done with https://github.com/YunoHost/apps/pull/772

**Comment by alexAubin** [comment]
Thanks ! :heart:
