### ISSUE TITLE
Looking for new maintainer⋅s

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/cheky_ynh#33]
Hello,

This YunoHost package is **looking for adoption**. But also, Cheky is **"end of life"**

I used to be an app maintainer for this package and I don't want to do that anymore. Feel free to take your hands on it.

I might explain myself on the forum later. Not sure if it's worth it? Let me know.

Regards,
Gofannon

-----------

@YunoHost-Apps/apps-group , the upsteam id "end of life", See this link in French https://forum.cheky.net/avenir-de-cheky-piost-t716-p1.html

I have no idea how to deal with this. Maybe this? https://github.com/YunoHost/apps#apps-flagged-as-not-maintained

in `apps.json`, changing `"maintained": false` ?

**Comment by yalh76** [comment]
> in apps.json, changing "maintained": false ?

Yes, it's the good solution

**Comment by alexAubin** [comment]
Closing because the app is defacto maintained by the yunohost community
