### ISSUE TITLE
update to 4.3.1

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/cheky_ynh#7]
Leboncoin blocked checky a while ago. Updating to 4.3.1 seems to solve the issue
https://github.com/Blount/Cheky/issues/93

Could you update the package ?
Thanks

**Comment by Gofannon** [comment]
Update to 4.3.3 available in test branch. (The upgrade worked on my server)

If you want to test, follow the instructions here https://github.com/YunoHost-Apps/cheky_ynh/blob/testing/README.md#informations-pour-d%C3%A9veloppeurs-et-d%C3%A9veloppeuses

**Comment by mokas01** [comment]
worked like a charm. Thanks
